name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run package

      - run: npm publish --access public
        env:
          NPM_CONFIG_PROVENANCE: true
